### ISSUE TITLE
UI and Styles: Create themes

### ISSUE THREAD

**Issue by Sw1ma** [Sw1ma/easycamper#9]
### Work Items
- [x] Default (device) theme 
- [x] Light theme
- [x] Dark theme
- [x] Theme Selection Page
- [x] Helper Classes and Dependency Services
